include: package:lints/recommended.yaml

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
    strict-inference: true

linter:
  rules:
    always_use_package_imports: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_double_and_int_checks: true
    avoid_equals_and_hash_code_on_mutable_classes: true
    avoid_escaping_inner_quotes: true
    avoid_field_initializers_in_const_classes: true
    avoid_js_rounded_ints: true
    avoid_positional_boolean_parameters: true
    avoid_print: true
    avoid_redundant_argument_values: true
    avoid_returning_this: true
    avoid_returning_null_for_future: true
    avoid_setters_without_getters: true
    avoid_slow_async_io: true
    avoid_type_to_string: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    cast_nullable_to_non_nullable: true
    deprecated_consistency: true
    directives_ordering: true
    eol_at_end_of_file: true
    join_return_with_assignment: true
    literal_only_boolean_expressions: true
    missing_whitespace_between_adjacent_strings: true
    no_default_cases: true
    noop_primitive_operations: true
    omit_local_variable_types: true
    parameter_assignments: true
    prefer_asserts_in_initializer_lists: true
    prefer_asserts_with_message: true
    prefer_const_constructors: true
    prefer_constructors_over_static_methods: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_int_literals: true
    prefer_null_aware_method_calls: true
    sort_constructors_first: true
    sort_pub_dependencies: true
    sort_unnamed_constructors_first: true
    tighten_type_of_initializing_formals: true
    type_annotate_public_apis: true
    unawaited_futures: true
    unnecessary_await_in_return: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    use_is_even_rather_than_modulo: true
    use_late_for_private_fields_and_variables: true
    use_named_constants: true
    use_raw_strings: true
    use_setters_to_change_properties: true
    use_string_buffers: true
    use_super_parameters: true
