name: git2dart
description: Dart bindings to libgit2, provides ability to use libgit2 library in Dart and Flutter.
repository: https://github.com/DartGit-dev/git2dart
version: 1.0.0

environment:
  sdk: ">=3.7.2 <4.0.0"
  flutter: ">=3.29.3"

dependencies:
  equatable: ^2.0.5
  ffi: ^2.0.1
  flutter:
    sdk: flutter

  git2dart_binaries: ^1.9.9
  meta: ^1.8.0
  path: ^1.8.1

dev_dependencies:
  lints: ^5.1.1
  test: ^1.20.0

platforms:
  linux:
  macos:
  windows:
