name: git2dart
description: Dart bindings to libgit2, provides ability to use libgit2 library in Dart and Flutter.
version: 0.0.1

environment:
  sdk: ">=2.19.2 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  equatable: ^2.0.5
  ffi: ^2.0.1
  git2dart_binaries: ^0.0.9
  meta: ^1.9.0
  path: ^1.8.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.20.0

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: Git2DartPlugin
