name: git2dart
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  equatable: ^2.0.5
  ffi: ^2.0.1
  git2dart_binaries: ^0.0.7
  meta: ^1.9.0
  path: ^1.8.1

dev_dependencies:
  ffigen: ^7.2.6
  lints: ^2.0.0
  test: ^1.20.0
