name: Publish

on:
  push:
    # tags:
    #   - "v[0-9]+.[0-9]+.[0-9]+*"
    branches: [main]
  # pull_request:
  #   branches: [main]
  workflow_dispatch:

env:
  PUB_ENVIRONMENT: bot.github

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        # platform: [ubuntu-latest, macos-latest, windows-latest]
        platform: [ubuntu-22.04]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Setup environment
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
    
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: |
          flutter pub get 
          dart format --output=none --set-exit-if-changed .
          flutter analyze --fatal-infos
          flutter test 

  publish:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Publish
        uses: k-paxian/dart-package-publisher@master
        with:
          accessToken: ${{ secrets.PUB_DEV_PUBLISH_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.PUB_DEV_PUBLISH_REFRESH_TOKEN }}
          flutter: true
          format: true
          dryRunOnly: true
          
