name: Publish

on:
  push:
    # tags:
    #   - "v[0-9]+.[0-9]+.[0-9]+*"
    branches: [main]
  # pull_request:
  #   branches: [main]
  workflow_dispatch:

env:
  PUB_ENVIRONMENT: bot.github

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Setup dependencies ubuntu
        if: ${{ matrix.platform == 'ubuntu-latest' }}
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt-get update -o Acquire::Retries=3 && sudo DEBIAN_FRONTEND=noninteractive apt-get install  -o Acquire::Retries=3 -y --no-install-recommends libssl-dev libpcre3

      - name: Setup dependencies macos
        if: ${{ matrix.platform == 'macos-latest' }}
        run: |
          brew install openssl

      - name: Setup dependencies windows
        if: ${{ matrix.platform == 'windows-latest' }}
        run: |
          choco install openssl -y

      - name: Setup environment
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
    
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: |
          flutter test 

  publish:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - run: |
          dart format --output=none --set-exit-if-changed .
          flutter analyze --fatal-infos

      - name: Publish
        uses: k-paxian/dart-package-publisher@master
        with:
          accessToken: ${{ secrets.PUB_DEV_PUBLISH_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.PUB_DEV_PUBLISH_REFRESH_TOKEN }}
          flutter: true
          format: true
          dryRunOnly: true
          
